### PR TITLE
Added Leetcode Python Programs Solution

### PR DESCRIPTION
**Pull request by Vaishnvee-Shinde**
Added Leetcode Python Programs Solution

### CODE REVIEW

**Review by BuddyCode — APPROVED** [review]
Fine

**Comment by Vaishnvee-Shinde** [comment]
Thank you @BuddyCode

**Comment by BuddyCode** [comment]
Don't you want to merge this PR? @Vaishnvee-Shinde

**Comment by Vaishnvee-Shinde** [comment]
> Don't you want to merge this PR? @Vaishnvee-Shinde

I want merge my PR @BuddyCode

**Comment by Vaishnvee-Shinde** [comment]
> Hey @BuddyCode  I thought you have merged my PR. Sorry it was by mistake closed the PR Request.

**Comment by BuddyCode** [comment]
Ok. No problem at all @Vaishnvee-Shinde

**Comment by Vaishnvee-Shinde** [comment]
> Ok. No problem at all @Vaishnvee-Shinde

@BuddyCode Thank You :)

**Comment by BuddyCode** [comment]
Can we connect on facebook/instagram @Vaishnvee-Shinde

**Comment by Vaishnvee-Shinde** [comment]
> Can we connect on facebook/instagram @Vaishnvee-Shinde

Hey @BuddyCode I have already joined your telegram group.

**Pull request merged**
