### PR TITLE
WEB DEVELOPMENT PROJECT

### PR DESCRIPTION
**Pull request by JAPJEET01**
this is a web development project related to online resume

### CODE REVIEW

**Review by JAPJEET01 — COMMENTED** [review]
created a online  resume website

**Comment by BuddyCode** [comment]
To complete this PR, you must STAR this Repo @JAPJEET01

**Comment by JAPJEET01** [comment]
> To complete this PR, you must STAR this Repo @JAPJEET01

Done sir

**Comment by JAPJEET01** [comment]
Done sir

**Comment by JAPJEET01** [comment]
> To complete this PR, you must STAR this Repo @JAPJEET01

sir  can you please accept my pull request as in my hactober fest it is showing as excluded  and no progress is increased

**Pull request merged**
